USE [DfSanatoriumDB]
GO

/****** Object:  Table [dbo].[apparatura]    Script Date: 18.03.2021 2:57:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[apparatura](
	[ID_аппаратуры] [int] IDENTITY(1,1) NOT NULL,
	[Описание] [nvarchar](250) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_аппаратуры] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


